version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config/loki.yml
    volumes:
      - ./loki.yml:/etc/loki/config/loki.yml

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./promtail.yml:/etc/promtail/config/promtail.yml
      - ./logs:/logs
    command: -config.file=/etc/promtail/config/promtail.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3000:3000"
    depends_on:
      - loki



