services:
  prometheus:
    image: prom/prometheus
    volumes:
      - D:\startUp\grafana-app\src\main\resources\prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
